# Use root/example as user/password credentials
version: '3.3'

services:

  mongo:
    image: 'mongo:latest'
    container_name: dhf-mongodb
    restart: always
    command: mongod --port 27018
    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: dhfadmin
      MONGO_INITDB_DATABASE: dhf-platform
    volumes:
      - /tmp/mongodb:/data/db
#      - mongodb_config:/data/configdb
    ports: 
      - "27018:27018"
#    command: mongo dhf-platform --eval "db.dropDatabase();"
